version: 2

sources:
  - name: raw_data
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
      - name: raw_gz_sales
        identifier: 
      - name: raw_gz_ship
        identifier: 